
import org.bbop.inca.SampleScala
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
//        def ss = new SampleScala()
//        ss.doSomething()

        new PredictionOne().runPrediction()
    }
}
