
import org.bbop.inca.SampleScala
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting
        println "A"
        def ss = new SampleScala()
        println "B"
        ss.doSomething()
        println "C"
    }
}
