
import org.bbop.inca.SampleScala
import org.bbop.inca.model.CatDogModel

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    static void main(String[] args) {

        File file = new CatDogModel().loadModel()

//        def ss = new SampleScala()
//        ss.doSomething()

        new PredictionOne().runPrediction()
    }
}
