
import org.bbop.inca.model.CatDogModel

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class CatDogApp {

    static void main(String[] args) {

        File file = new CatDogModel().loadModel()

        new PredictionOne().runPrediction()
    }
}
