/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

//import play.api.libs.json.Json
import groovy.json.JsonSlurper
import spock.lang.Specification


class CatDogAppTest extends Specification {
    def "application can recognize dogs and cats"() {
        setup:
        String jsonResult = CatDogApp.evaluateFigures()

        when:
//        println "json result ->${jsonResult}"
        def result = new JsonSlurper().parseText(jsonResult)

        then:
        result != null
        for(r in result){
            assert r.name.contains(r.result.toLowerCase())
        }
    }
}
